# Generated by Django 3.1.6 on 2021-03-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbupApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
