# Generated by Django 3.1.6 on 2021-03-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbupApp', '0002_auto_20210315_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
